%This program derives the average voltage, rpm, and efficiency of both turbines at each resistance, and plots them in 
%order to possibly reveal significant trends between resistance and the different variables, and to compare the 
%performances of the turbines side by side.
close all
clear all
clc

velocity= 5; %enter wind velocity of fan in m/s
sweptA= 0.245161; %enter swept area of angel turbine
sweptH= 0.232258; %enter swept area of horse turbine

avaPowA=1/2*1.23*sweptA*velocity^3;%avalible power for angel turbine
avaPowH=1/2*1.23*sweptH*velocity^3;%avalible power for horse turbine

E = [.05, .1, .2, .3, .4, .5, .59]; %vector of predicted effeciencies
prePowA=[];%stores predicted power values
prePowH=[];
n=1;
while(n<=length(E))%fills in predicted power values
    prePowA(n)=(avaPowA*E(n));
    prePowH(n)=(avaPowH*E(n));
    n=n+1;
end

%plots predicted data
plot(E, prePowA, '-o');
hold on
plot(E, prePowH, '-o');
xlabel('Effeciency');
ylabel('Power(Watts)');
title('Power Generated vs. Predicted Effeciencies');
hold off

R = [1.2, 1.5, 1.8, 2, 2.4, 2.7, 3.6, 5.6, 8.2, 10, 12, 15, 18, 24]; %creates a vector of all the different resistance values
AngelData = load('AngelTestData.csv');
HorseData = load('HorseTestData.csv');
%creates vectors of the Voltage values for the Angel model corresponding
%with each resistance value
VmeanA=[];%angel voltage
VmeanH=[];%horse voltage
RmeanA=[];%angel rpm
RmeanH=[];%horse rpm
powA=[];%angel efficiency
powH=[];%horse efficiency
maxPowA=0;%stores max power generated by angel
maxPowH=0;%stores max power generated by horse
goodResA=0;%stores best resistance for power generation from Angel
goodResH=0;%stores best resistance for power generation from Horse
n=1;
I1=1;
I2=25;
while(n<=14)%Fills Arrays
	VmeanA(n)=mean(AngelData(I1:I2, 2));
	RmeanA(n)=mean(AngelData(I1:I2, 3));
	VmeanH(n)=mean(HorseData(I1:I2, 2));
	RmeanH(n)=mean(HorseData(I1:I2, 3));
    powA(n)=(VmeanA(n))^2/R(n)/(avaPowA);%voltage^2/resistance/avalible power=effeciency
    powH(n)=(VmeanH(n))^2/R(n)/(avaPowH);
    if powA(n)>maxPowA%finds max power generated
        maxPowA=powA(n)*avaPowA;
        goodResA = R(n);
    end
    if powH(n)>maxPowH
        maxPowH=powH(n)*avaPowH;
        goodResH = R(n);
    end
	I1=I1+25;%Resistance changes every 25 readings
	I2=I2+25;
	n=n+1;
end

%plots nessesary recorded data
figure
plot(R, VmeanA, '-o');
hold on
plot(R, VmeanH, '-o');
xlabel('Resistance(Ohms)');
ylabel('Voltage(Volts)');
title('Voltage Generated by Turbines vs. Resistance');
hold off
 
figure
plot(R, RmeanA, '-o');
hold on
plot(R, RmeanH, '-o');
xlabel('Resistance(Ohms)');
ylabel('RPM');
title('RPM of Turbines vs. Resistance');
hold off
 
figure
plot(R, powA, '-o');
hold on
plot(R, powH, '-o');
xlabel('Resistance(Ohms)');
ylabel('Efficiency');
title('Efficiency of Turbines vs. Resistance');
hold off

figure
plot(R, powA*(avaPowA), '-o');
hold on
plot(R, powH*(avaPowH), '-o');
xlabel('Resistance(Ohms)');
ylabel('Power(Watts)');
title('Power Generated by Turbines vs. Resistance');
hold off

%displays avalible power and max power generated at specified resistance
display('Avalible power from the wind for the Angel Turbine: ')
fprintf('%.4f watts.\n',avaPowA)
display('Max power generated by Angel Turbine: ')
fprintf('%.4f watts at %.2f ohms .\n',maxPowA, goodResA)
display('Avalible power from the wind for Horse Turbine: ')
fprintf('%.4f watts.\n',avaPowH)
display('Max power generated by Horse Turbine: ')
fprintf('%.4f watts at %.2f ohms.\n',maxPowH, goodResH)
